//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExaminationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.Results = new HashSet<Result>();
            this.TemporaryTests = new HashSet<TemporaryTest>();
        }
    
        public int ExamId { get; set; }
        public int CourseID { get; set; }
        public int TeacherId { get; set; }
        public int QuestionId { get; set; }
        public string Attendents { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<bool> isOnline { get; set; }
        public Nullable<bool> isCatagorized { get; set; }
        public string Categories { get; set; }
        public Nullable<int> NoOfQuestion { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Question Question { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemporaryTest> TemporaryTests { get; set; }
    }
}
